[config.wallpaper]
command = "swww"
arguments = ["img", "-t", "grow", "--transition-pos", "0.75,0.6"]
set = true

[templates.waybar]
input_path = './templates/waybar.template'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'
